name: AEW Weekly Contributions

on:
  schedule:
    - cron: "0 14 * * 0"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  check-contributions:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./recap

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Run contribution checker
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          WEBHOOK_URL: ${{ secrets.AEW_WEBHOOK_URL }}
          CHANNEL_ID: "1362097950934695946"
          FANDOM_SUBDOMAIN: "alter-ego"
          EMBED_COLOR: "0099ff"
          PROJECT_DIR: "aew"
        run: bun run index.js

      - name: Commit push
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
          git add ../data/recap/aew/
          git diff --cached --quiet || (git commit -m "chore: aew weekly data" && git push)
